name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "docs: generate contribution snake" || exit 0
          git push
